-- LEITO360 -- Bloco 2/4: LEITO360_CNES_JSON (DDL + 162 INSERTs)
DROP TABLE LEITO360_CNES_JSON CASCADE CONSTRAINTS PURGE;

CREATE TABLE LEITO360_CNES_JSON (
    id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    doc  JSON NOT NULL
);

CREATE INDEX ix_leito360_cnes_json_comp_uf
    ON LEITO360_CNES_JSON (JSON_VALUE(doc, '$.competencia'), JSON_VALUE(doc, '$.codigo_uf'));

INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "11", "sigla_uf": "RO", "estado": "Rondônia", "regiao": "Norte", "leitos_sus_cadastrados": 4265}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "12", "sigla_uf": "AC", "estado": "Acre", "regiao": "Norte", "leitos_sus_cadastrados": 1458}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "13", "sigla_uf": "AM", "estado": "Amazonas", "regiao": "Norte", "leitos_sus_cadastrados": 5490}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "14", "sigla_uf": "RR", "estado": "Roraima", "regiao": "Norte", "leitos_sus_cadastrados": 1332}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "15", "sigla_uf": "PA", "estado": "Pará", "regiao": "Norte", "leitos_sus_cadastrados": 11466}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "16", "sigla_uf": "AP", "estado": "Amapá", "regiao": "Norte", "leitos_sus_cadastrados": 1387}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "17", "sigla_uf": "TO", "estado": "Tocantins", "regiao": "Norte", "leitos_sus_cadastrados": 2742}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "21", "sigla_uf": "MA", "estado": "Maranhão", "regiao": "Nordeste", "leitos_sus_cadastrados": 13194}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "22", "sigla_uf": "PI", "estado": "Piauí", "regiao": "Nordeste", "leitos_sus_cadastrados": 6134}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "23", "sigla_uf": "CE", "estado": "Ceará", "regiao": "Nordeste", "leitos_sus_cadastrados": 16178}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "24", "sigla_uf": "RN", "estado": "Rio Grande do Norte", "regiao": "Nordeste", "leitos_sus_cadastrados": 6209}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "25", "sigla_uf": "PB", "estado": "Paraíba", "regiao": "Nordeste", "leitos_sus_cadastrados": 7496}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "26", "sigla_uf": "PE", "estado": "Pernambuco", "regiao": "Nordeste", "leitos_sus_cadastrados": 16092}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "27", "sigla_uf": "AL", "estado": "Alagoas", "regiao": "Nordeste", "leitos_sus_cadastrados": 5385}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "28", "sigla_uf": "SE", "estado": "Sergipe", "regiao": "Nordeste", "leitos_sus_cadastrados": 2729}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "29", "sigla_uf": "BA", "estado": "Bahia", "regiao": "Nordeste", "leitos_sus_cadastrados": 24844}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "31", "sigla_uf": "MG", "estado": "Minas Gerais", "regiao": "Sudeste", "leitos_sus_cadastrados": 29380}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "32", "sigla_uf": "ES", "estado": "Espírito Santo", "regiao": "Sudeste", "leitos_sus_cadastrados": 5952}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "33", "sigla_uf": "RJ", "estado": "Rio de Janeiro", "regiao": "Sudeste", "leitos_sus_cadastrados": 20976}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "35", "sigla_uf": "SP", "estado": "São Paulo", "regiao": "Sudeste", "leitos_sus_cadastrados": 54619}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "41", "sigla_uf": "PR", "estado": "Paraná", "regiao": "Sul", "leitos_sus_cadastrados": 19333}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "42", "sigla_uf": "SC", "estado": "Santa Catarina", "regiao": "Sul", "leitos_sus_cadastrados": 11787}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "43", "sigla_uf": "RS", "estado": "Rio Grande do Sul", "regiao": "Sul", "leitos_sus_cadastrados": 20285}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "50", "sigla_uf": "MS", "estado": "Mato Grosso do Sul", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4034}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "51", "sigla_uf": "MT", "estado": "Mato Grosso", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 6032}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "52", "sigla_uf": "GO", "estado": "Goiás", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 12054}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-11", "codigo_uf": "53", "sigla_uf": "DF", "estado": "Distrito Federal", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4880}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "11", "sigla_uf": "RO", "estado": "Rondônia", "regiao": "Norte", "leitos_sus_cadastrados": 4301}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "12", "sigla_uf": "AC", "estado": "Acre", "regiao": "Norte", "leitos_sus_cadastrados": 1458}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "13", "sigla_uf": "AM", "estado": "Amazonas", "regiao": "Norte", "leitos_sus_cadastrados": 5497}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "14", "sigla_uf": "RR", "estado": "Roraima", "regiao": "Norte", "leitos_sus_cadastrados": 1332}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "15", "sigla_uf": "PA", "estado": "Pará", "regiao": "Norte", "leitos_sus_cadastrados": 11491}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "16", "sigla_uf": "AP", "estado": "Amapá", "regiao": "Norte", "leitos_sus_cadastrados": 1387}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "17", "sigla_uf": "TO", "estado": "Tocantins", "regiao": "Norte", "leitos_sus_cadastrados": 2730}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "21", "sigla_uf": "MA", "estado": "Maranhão", "regiao": "Nordeste", "leitos_sus_cadastrados": 13354}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "22", "sigla_uf": "PI", "estado": "Piauí", "regiao": "Nordeste", "leitos_sus_cadastrados": 6162}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "23", "sigla_uf": "CE", "estado": "Ceará", "regiao": "Nordeste", "leitos_sus_cadastrados": 16141}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "24", "sigla_uf": "RN", "estado": "Rio Grande do Norte", "regiao": "Nordeste", "leitos_sus_cadastrados": 6223}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "25", "sigla_uf": "PB", "estado": "Paraíba", "regiao": "Nordeste", "leitos_sus_cadastrados": 7540}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "26", "sigla_uf": "PE", "estado": "Pernambuco", "regiao": "Nordeste", "leitos_sus_cadastrados": 16084}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "27", "sigla_uf": "AL", "estado": "Alagoas", "regiao": "Nordeste", "leitos_sus_cadastrados": 5519}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "28", "sigla_uf": "SE", "estado": "Sergipe", "regiao": "Nordeste", "leitos_sus_cadastrados": 2735}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "29", "sigla_uf": "BA", "estado": "Bahia", "regiao": "Nordeste", "leitos_sus_cadastrados": 24832}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "31", "sigla_uf": "MG", "estado": "Minas Gerais", "regiao": "Sudeste", "leitos_sus_cadastrados": 29348}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "32", "sigla_uf": "ES", "estado": "Espírito Santo", "regiao": "Sudeste", "leitos_sus_cadastrados": 6039}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "33", "sigla_uf": "RJ", "estado": "Rio de Janeiro", "regiao": "Sudeste", "leitos_sus_cadastrados": 21051}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "35", "sigla_uf": "SP", "estado": "São Paulo", "regiao": "Sudeste", "leitos_sus_cadastrados": 54645}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "41", "sigla_uf": "PR", "estado": "Paraná", "regiao": "Sul", "leitos_sus_cadastrados": 19403}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "42", "sigla_uf": "SC", "estado": "Santa Catarina", "regiao": "Sul", "leitos_sus_cadastrados": 11822}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "43", "sigla_uf": "RS", "estado": "Rio Grande do Sul", "regiao": "Sul", "leitos_sus_cadastrados": 20350}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "50", "sigla_uf": "MS", "estado": "Mato Grosso do Sul", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4033}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "51", "sigla_uf": "MT", "estado": "Mato Grosso", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 6089}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "52", "sigla_uf": "GO", "estado": "Goiás", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 12050}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2025-12", "codigo_uf": "53", "sigla_uf": "DF", "estado": "Distrito Federal", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4913}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "11", "sigla_uf": "RO", "estado": "Rondônia", "regiao": "Norte", "leitos_sus_cadastrados": 4301}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "12", "sigla_uf": "AC", "estado": "Acre", "regiao": "Norte", "leitos_sus_cadastrados": 1462}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "13", "sigla_uf": "AM", "estado": "Amazonas", "regiao": "Norte", "leitos_sus_cadastrados": 5466}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "14", "sigla_uf": "RR", "estado": "Roraima", "regiao": "Norte", "leitos_sus_cadastrados": 1332}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "15", "sigla_uf": "PA", "estado": "Pará", "regiao": "Norte", "leitos_sus_cadastrados": 11411}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "16", "sigla_uf": "AP", "estado": "Amapá", "regiao": "Norte", "leitos_sus_cadastrados": 1389}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "17", "sigla_uf": "TO", "estado": "Tocantins", "regiao": "Norte", "leitos_sus_cadastrados": 2777}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "21", "sigla_uf": "MA", "estado": "Maranhão", "regiao": "Nordeste", "leitos_sus_cadastrados": 13347}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "22", "sigla_uf": "PI", "estado": "Piauí", "regiao": "Nordeste", "leitos_sus_cadastrados": 6124}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "23", "sigla_uf": "CE", "estado": "Ceará", "regiao": "Nordeste", "leitos_sus_cadastrados": 15964}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "24", "sigla_uf": "RN", "estado": "Rio Grande do Norte", "regiao": "Nordeste", "leitos_sus_cadastrados": 6215}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "25", "sigla_uf": "PB", "estado": "Paraíba", "regiao": "Nordeste", "leitos_sus_cadastrados": 7554}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "26", "sigla_uf": "PE", "estado": "Pernambuco", "regiao": "Nordeste", "leitos_sus_cadastrados": 16169}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "27", "sigla_uf": "AL", "estado": "Alagoas", "regiao": "Nordeste", "leitos_sus_cadastrados": 5528}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "28", "sigla_uf": "SE", "estado": "Sergipe", "regiao": "Nordeste", "leitos_sus_cadastrados": 2732}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "29", "sigla_uf": "BA", "estado": "Bahia", "regiao": "Nordeste", "leitos_sus_cadastrados": 24857}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "31", "sigla_uf": "MG", "estado": "Minas Gerais", "regiao": "Sudeste", "leitos_sus_cadastrados": 29233}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "32", "sigla_uf": "ES", "estado": "Espírito Santo", "regiao": "Sudeste", "leitos_sus_cadastrados": 6061}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "33", "sigla_uf": "RJ", "estado": "Rio de Janeiro", "regiao": "Sudeste", "leitos_sus_cadastrados": 21035}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "35", "sigla_uf": "SP", "estado": "São Paulo", "regiao": "Sudeste", "leitos_sus_cadastrados": 54770}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "41", "sigla_uf": "PR", "estado": "Paraná", "regiao": "Sul", "leitos_sus_cadastrados": 19404}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "42", "sigla_uf": "SC", "estado": "Santa Catarina", "regiao": "Sul", "leitos_sus_cadastrados": 11761}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "43", "sigla_uf": "RS", "estado": "Rio Grande do Sul", "regiao": "Sul", "leitos_sus_cadastrados": 20346}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "50", "sigla_uf": "MS", "estado": "Mato Grosso do Sul", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4040}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "51", "sigla_uf": "MT", "estado": "Mato Grosso", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 6108}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "52", "sigla_uf": "GO", "estado": "Goiás", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 11996}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-01", "codigo_uf": "53", "sigla_uf": "DF", "estado": "Distrito Federal", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4957}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "11", "sigla_uf": "RO", "estado": "Rondônia", "regiao": "Norte", "leitos_sus_cadastrados": 4304}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "12", "sigla_uf": "AC", "estado": "Acre", "regiao": "Norte", "leitos_sus_cadastrados": 1470}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "13", "sigla_uf": "AM", "estado": "Amazonas", "regiao": "Norte", "leitos_sus_cadastrados": 5470}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "14", "sigla_uf": "RR", "estado": "Roraima", "regiao": "Norte", "leitos_sus_cadastrados": 1332}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "15", "sigla_uf": "PA", "estado": "Pará", "regiao": "Norte", "leitos_sus_cadastrados": 11517}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "16", "sigla_uf": "AP", "estado": "Amapá", "regiao": "Norte", "leitos_sus_cadastrados": 1391}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "17", "sigla_uf": "TO", "estado": "Tocantins", "regiao": "Norte", "leitos_sus_cadastrados": 2777}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "21", "sigla_uf": "MA", "estado": "Maranhão", "regiao": "Nordeste", "leitos_sus_cadastrados": 13339}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "22", "sigla_uf": "PI", "estado": "Piauí", "regiao": "Nordeste", "leitos_sus_cadastrados": 6129}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "23", "sigla_uf": "CE", "estado": "Ceará", "regiao": "Nordeste", "leitos_sus_cadastrados": 15944}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "24", "sigla_uf": "RN", "estado": "Rio Grande do Norte", "regiao": "Nordeste", "leitos_sus_cadastrados": 6226}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "25", "sigla_uf": "PB", "estado": "Paraíba", "regiao": "Nordeste", "leitos_sus_cadastrados": 7558}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "26", "sigla_uf": "PE", "estado": "Pernambuco", "regiao": "Nordeste", "leitos_sus_cadastrados": 16096}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "27", "sigla_uf": "AL", "estado": "Alagoas", "regiao": "Nordeste", "leitos_sus_cadastrados": 5558}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "28", "sigla_uf": "SE", "estado": "Sergipe", "regiao": "Nordeste", "leitos_sus_cadastrados": 2731}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "29", "sigla_uf": "BA", "estado": "Bahia", "regiao": "Nordeste", "leitos_sus_cadastrados": 24712}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "31", "sigla_uf": "MG", "estado": "Minas Gerais", "regiao": "Sudeste", "leitos_sus_cadastrados": 29339}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "32", "sigla_uf": "ES", "estado": "Espírito Santo", "regiao": "Sudeste", "leitos_sus_cadastrados": 5970}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "33", "sigla_uf": "RJ", "estado": "Rio de Janeiro", "regiao": "Sudeste", "leitos_sus_cadastrados": 21025}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "35", "sigla_uf": "SP", "estado": "São Paulo", "regiao": "Sudeste", "leitos_sus_cadastrados": 54700}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "41", "sigla_uf": "PR", "estado": "Paraná", "regiao": "Sul", "leitos_sus_cadastrados": 19414}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "42", "sigla_uf": "SC", "estado": "Santa Catarina", "regiao": "Sul", "leitos_sus_cadastrados": 11787}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "43", "sigla_uf": "RS", "estado": "Rio Grande do Sul", "regiao": "Sul", "leitos_sus_cadastrados": 20345}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "50", "sigla_uf": "MS", "estado": "Mato Grosso do Sul", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4042}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "51", "sigla_uf": "MT", "estado": "Mato Grosso", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 6118}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "52", "sigla_uf": "GO", "estado": "Goiás", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 11969}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-02", "codigo_uf": "53", "sigla_uf": "DF", "estado": "Distrito Federal", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4964}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "11", "sigla_uf": "RO", "estado": "Rondônia", "regiao": "Norte", "leitos_sus_cadastrados": 4203}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "12", "sigla_uf": "AC", "estado": "Acre", "regiao": "Norte", "leitos_sus_cadastrados": 1470}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "13", "sigla_uf": "AM", "estado": "Amazonas", "regiao": "Norte", "leitos_sus_cadastrados": 5509}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "14", "sigla_uf": "RR", "estado": "Roraima", "regiao": "Norte", "leitos_sus_cadastrados": 1348}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "15", "sigla_uf": "PA", "estado": "Pará", "regiao": "Norte", "leitos_sus_cadastrados": 11571}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "16", "sigla_uf": "AP", "estado": "Amapá", "regiao": "Norte", "leitos_sus_cadastrados": 1440}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "17", "sigla_uf": "TO", "estado": "Tocantins", "regiao": "Norte", "leitos_sus_cadastrados": 2870}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "21", "sigla_uf": "MA", "estado": "Maranhão", "regiao": "Nordeste", "leitos_sus_cadastrados": 13300}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "22", "sigla_uf": "PI", "estado": "Piauí", "regiao": "Nordeste", "leitos_sus_cadastrados": 6129}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "23", "sigla_uf": "CE", "estado": "Ceará", "regiao": "Nordeste", "leitos_sus_cadastrados": 15938}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "24", "sigla_uf": "RN", "estado": "Rio Grande do Norte", "regiao": "Nordeste", "leitos_sus_cadastrados": 6284}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "25", "sigla_uf": "PB", "estado": "Paraíba", "regiao": "Nordeste", "leitos_sus_cadastrados": 7566}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "26", "sigla_uf": "PE", "estado": "Pernambuco", "regiao": "Nordeste", "leitos_sus_cadastrados": 16021}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "27", "sigla_uf": "AL", "estado": "Alagoas", "regiao": "Nordeste", "leitos_sus_cadastrados": 5406}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "28", "sigla_uf": "SE", "estado": "Sergipe", "regiao": "Nordeste", "leitos_sus_cadastrados": 2756}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "29", "sigla_uf": "BA", "estado": "Bahia", "regiao": "Nordeste", "leitos_sus_cadastrados": 24916}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "31", "sigla_uf": "MG", "estado": "Minas Gerais", "regiao": "Sudeste", "leitos_sus_cadastrados": 29389}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "32", "sigla_uf": "ES", "estado": "Espírito Santo", "regiao": "Sudeste", "leitos_sus_cadastrados": 5987}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "33", "sigla_uf": "RJ", "estado": "Rio de Janeiro", "regiao": "Sudeste", "leitos_sus_cadastrados": 21105}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "35", "sigla_uf": "SP", "estado": "São Paulo", "regiao": "Sudeste", "leitos_sus_cadastrados": 54688}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "41", "sigla_uf": "PR", "estado": "Paraná", "regiao": "Sul", "leitos_sus_cadastrados": 19421}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "42", "sigla_uf": "SC", "estado": "Santa Catarina", "regiao": "Sul", "leitos_sus_cadastrados": 11770}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "43", "sigla_uf": "RS", "estado": "Rio Grande do Sul", "regiao": "Sul", "leitos_sus_cadastrados": 20252}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "50", "sigla_uf": "MS", "estado": "Mato Grosso do Sul", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4039}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "51", "sigla_uf": "MT", "estado": "Mato Grosso", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 6158}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "52", "sigla_uf": "GO", "estado": "Goiás", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 11904}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-03", "codigo_uf": "53", "sigla_uf": "DF", "estado": "Distrito Federal", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 5014}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "11", "sigla_uf": "RO", "estado": "Rondônia", "regiao": "Norte", "leitos_sus_cadastrados": 4167}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "12", "sigla_uf": "AC", "estado": "Acre", "regiao": "Norte", "leitos_sus_cadastrados": 1422}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "13", "sigla_uf": "AM", "estado": "Amazonas", "regiao": "Norte", "leitos_sus_cadastrados": 5503}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "14", "sigla_uf": "RR", "estado": "Roraima", "regiao": "Norte", "leitos_sus_cadastrados": 1348}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "15", "sigla_uf": "PA", "estado": "Pará", "regiao": "Norte", "leitos_sus_cadastrados": 11614}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "16", "sigla_uf": "AP", "estado": "Amapá", "regiao": "Norte", "leitos_sus_cadastrados": 1422}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "17", "sigla_uf": "TO", "estado": "Tocantins", "regiao": "Norte", "leitos_sus_cadastrados": 2870}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "21", "sigla_uf": "MA", "estado": "Maranhão", "regiao": "Nordeste", "leitos_sus_cadastrados": 13301}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "22", "sigla_uf": "PI", "estado": "Piauí", "regiao": "Nordeste", "leitos_sus_cadastrados": 6152}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "23", "sigla_uf": "CE", "estado": "Ceará", "regiao": "Nordeste", "leitos_sus_cadastrados": 15969}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "24", "sigla_uf": "RN", "estado": "Rio Grande do Norte", "regiao": "Nordeste", "leitos_sus_cadastrados": 6220}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "25", "sigla_uf": "PB", "estado": "Paraíba", "regiao": "Nordeste", "leitos_sus_cadastrados": 7543}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "26", "sigla_uf": "PE", "estado": "Pernambuco", "regiao": "Nordeste", "leitos_sus_cadastrados": 16025}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "27", "sigla_uf": "AL", "estado": "Alagoas", "regiao": "Nordeste", "leitos_sus_cadastrados": 5406}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "28", "sigla_uf": "SE", "estado": "Sergipe", "regiao": "Nordeste", "leitos_sus_cadastrados": 2760}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "29", "sigla_uf": "BA", "estado": "Bahia", "regiao": "Nordeste", "leitos_sus_cadastrados": 25005}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "31", "sigla_uf": "MG", "estado": "Minas Gerais", "regiao": "Sudeste", "leitos_sus_cadastrados": 29778}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "32", "sigla_uf": "ES", "estado": "Espírito Santo", "regiao": "Sudeste", "leitos_sus_cadastrados": 5971}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "33", "sigla_uf": "RJ", "estado": "Rio de Janeiro", "regiao": "Sudeste", "leitos_sus_cadastrados": 21061}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "35", "sigla_uf": "SP", "estado": "São Paulo", "regiao": "Sudeste", "leitos_sus_cadastrados": 54722}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "41", "sigla_uf": "PR", "estado": "Paraná", "regiao": "Sul", "leitos_sus_cadastrados": 19319}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "42", "sigla_uf": "SC", "estado": "Santa Catarina", "regiao": "Sul", "leitos_sus_cadastrados": 11778}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "43", "sigla_uf": "RS", "estado": "Rio Grande do Sul", "regiao": "Sul", "leitos_sus_cadastrados": 20100}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "50", "sigla_uf": "MS", "estado": "Mato Grosso do Sul", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 4058}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "51", "sigla_uf": "MT", "estado": "Mato Grosso", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 6099}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "52", "sigla_uf": "GO", "estado": "Goiás", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 11622}');
INSERT INTO LEITO360_CNES_JSON (doc) VALUES ('{"competencia": "2026-04", "codigo_uf": "53", "sigla_uf": "DF", "estado": "Distrito Federal", "regiao": "Centro-Oeste", "leitos_sus_cadastrados": 5000}');
COMMIT;
SELECT COUNT(*) FROM LEITO360_CNES_JSON WHERE doc IS JSON; -- esperado: 162